// <auto-generated />
using System;
using Gas_Station.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gas_Station.EF.Migrations
{
    [DbContext(typeof(GasStationContext))]
    [Migration("20220411113151_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gas_Station.Model.Customer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Gas_Station.Model.Employee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeType")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDateEnd")
                        .HasMaxLength(30)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HireDateStart")
                        .HasMaxLength(30)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("SallaryPerMonth")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Employeess", (string)null);
                });

            modelBuilder.Entity("Gas_Station.Model.Item", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Cost")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ItemType")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Gas_Station.Model.Ledger", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Expenses")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Income")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ledgers", (string)null);
                });

            modelBuilder.Entity("Gas_Station.Model.Transaction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerID")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethod")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID1");

                    b.HasIndex("EmployeeID1");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Gas_Station.Model.TransactionLine", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountPercent")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountValue")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemID")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<Guid>("ItemID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ItemPrice")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetValue")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionID")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionID1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ItemID1");

                    b.HasIndex("TransactionID1");

                    b.ToTable("TransactionLines", (string)null);
                });

            modelBuilder.Entity("Gas_Station.Model.Transaction", b =>
                {
                    b.HasOne("Gas_Station.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gas_Station.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Gas_Station.Model.TransactionLine", b =>
                {
                    b.HasOne("Gas_Station.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gas_Station.Model.Transaction", "Transaction")
                        .WithMany("TransactionLines")
                        .HasForeignKey("TransactionID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Gas_Station.Model.Transaction", b =>
                {
                    b.Navigation("TransactionLines");
                });
#pragma warning restore 612, 618
        }
    }
}
